spring:
  application:
    name: lana-server

server:
  port: 8081

security:
  username: ${USERNAME}
  password: ${PASSWORD}

data:
  products: /data/products.json
  promotions: /data/promotions.json
